compressionLevel: mixed

enableGlobalCache: false

enableStrictSsl: true

httpTimeout: 60000

networkConcurrency: 8

nodeLinker: pnp

packageExtensions:
  '@vitejs/plugin-react@*':
    dependencies:
      vite: '*'
  debug@*:
    dependencies:
      supports-color: '*'
  eslint-config-next@*:
    dependencies:
      '@rushstack/eslint-patch': '*'
      eslint: '*'

pnpMode: loose

yarnPath: .yarn/releases/yarn-4.12.0.cjs
