compressionLevel: mixed

enableGlobalCache: false

enableTelemetry: false

nodeLinker: pnp

packageExtensions:
  "@vitejs/plugin-react@*":
    peerDependencies:
      vite: "*"

yarnPath: .yarn/releases/yarn-4.10.3.cjs
