# Use Plug'n'Play installation mode
nodeLinker: pnp

# Use loose mode for better compatibility with some packages
pnpMode: loose

# Yarn release version
yarnPath: .yarn/releases/yarn-4.1.0.cjs

# Enable zero-installs (optional but recommended for CI)
enableGlobalCache: false

# Package extensions to fix peer dependency issues
packageExtensions:
  '@vitejs/plugin-react@*':
    dependencies:
      vite: '*'

  # Add more extensions if needed for other packages
  'vitest@*':
    dependencies:
      vite: '*'

# Compression settings for cache
compressionLevel: mixed

# Network settings for CI reliability
httpTimeout: 60000
networkConcurrency: 8

# Enable strict SSL for security
enableStrictSsl: true
